spring:
  application:
    name: oauth2-server
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/changsha?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
    hikari:
      minimum-idle: 5
      idle-timeout: 600000
      maximum-pool-size: 10
      auto-commit: true
      pool-name: MyHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1

server:
  undertow:
    direct-buffers: true
    io-threads: 4
#    worker-threads: 256
  port: 8080

#server:
#  port: 8080
#  tomcat:
#    max-threads: 200

mybatis:
  type-aliases-package: com.windthunder.machineroom.monitoring.domain
  mapper-locations: classpath:mapper/*.xml